collections:
  - id: 'team'
    path: '.pages/team'
    label: 'Team Members'
    fields:
      - name: 'name'
        label: 'Name'
        type: 'string'
      - name: 'role'
        label: 'Role'
        type: 'string'
      - name: 'bio'
        label: 'Bio'
        type: 'rich-text'
      - name: 'linkedin'
        label: 'LinkedIn URL'
        type: 'string'

  - id: 'expertise'
    path: '.pages/expertise'
    label: 'Areas of Expertise'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'string'
      - name: 'description'
        label: 'Description'
        type: 'rich-text'
      - name: 'services'
        label: 'Services'
        type: 'list'
        of:
          type: 'string'
  
  - id: 'portfolio'
    path: '.pages/portfolio'
    label: 'Portfolio Companies'
    fields:
      - name: 'name'
        label: 'Company Name'
        type: 'string'
      - name: 'logo'
        label: 'Company Logo'
        type: 'image'
      - name: 'website'
        label: 'Website URL'
        type: 'string'
      - name: 'description'
        label: 'Description'
        type: 'rich-text'
      - name: 'images'
        label: 'Gallery Images'
        type: 'list'
        of:
          type: 'image'

  - id: 'blog'
    path: '.pages/blog'
    label: 'Blog Posts'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'string'
      - name: 'author'
        label: 'Author'
        type: 'reference'
        collection: 'team'
      - name: 'case_study_for'
        label: 'Case Study For (Company)'
        type: 'reference'
        collection: 'portfolio'
      - name: 'publishedDate'
        label: 'Published Date'
        type: 'date'
      - name: 'body'
        label: 'Body'
        type: 'rich-text'